# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            A Short History of Sushi
tagline:          By Team Sushi
url:              /
paginate:         100
baseurl:          /
team:             Team Sushi
author:
  name:           David Kua
  url:            https://github.com/dkua
  email:          david.kua@mail.utoronto.ca

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/dkua/team-sushi
